### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Isanur960** [clovaai/stargan-v2-tensorflow#9]
I am getting this error in Colab

`

Traceback (most recent call last):
  File "main.py", line 117, in <module>
    main()
  File "main.py", line 103, in main
    gan.build_model()
  File "/content/stargan-v2-tensorflow/StarGAN_v2.py", line 197, in build_model
    self.mapping_network_ema = MappingNetwork(self.style_dim, self.hidden_dim, self.num_domains, sn=False, name='MappingNetwork')
  File "/content/stargan-v2-tensorflow/networks.py", line 85, in __init__
    self.shared_layers, self.unshared_layers = self.architecture_init()
  File "/content/stargan-v2-tensorflow/networks.py", line 96, in architecture_init
    shared_layers = Sequential(layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 142, in __init__
    self.add(layer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 189, in add
    'to pass a unique name.' % (layer.name,))
ValueError: All layers added to a Sequential model should have unique names. Name "relu" is already the name of a layer in this model. Update the `name` argument to pass a unique name `

**Comment by ruanjiyang** [comment]
I got the same issues and need help.

**Comment by baymak** [comment]
I had worked around of this issue just by changing the names of relu and leaky relu activations layers as mentioned in the ValueError. There are a couple of layers.

**Comment by Nick-Sun1018** [comment]
> I had worked around of this issue just by changing the names of relu and leaky relu activations layers as mentioned in the ValueError. There are a couple of layers.

Thank you, it works!
